### ISSUE TITLE
UI enhancements for noise gate demo

### ISSUE THREAD

**Issue by rtoy** [GoogleChromeLabs/web-audio-samples#104]
In the [noisegate demo](http://googlechrome.github.io/web-audio-samples/audio-worklet/noisegate.html), a couple of the UI elements could be improved a bit. In no particular order:

- In a browser without AudioWorklet support, the worklet button is properly greyed out.  But that's hard to see.  Perhaps the text should also be greyed our or something to make it easier to tell that worklets are supported.
- When the noise gate is bypassed, the threshold, attack, and release sliders don't work.  This is ok, but there's no indication of that on the sliders themselves.  Perhaps they should be greyed out or something to indicate that the sliders are disabled.
- Very minor issue:  It would be nice if the noisegate sliders were separated a bit from the volume sliders to make the distinction clearer on what controls the noise gate and doesn't.

**Comment by hoch** [comment]
The project does not exist in this repository. Closing.
