### ISSUE TITLE
Poly-synth note-never-ends bug

### ISSUE THREAD

**Issue by samhincks** [GoogleChromeLabs/web-audio-samples#108]
If you press a note with the keyboard and then press the same note with the mouse, the note will play forever even when released by the GUI.

To fix this issue, either the data structure used to manage voices needs to be changed or the third party[ keyboard GUI ](https://raw.githubusercontent.com/stuartmemo/qwerty-hancock/master/dist/qwerty-hancock.js)needs to be modified to disable mouse input.

**Comment by hoch** [comment]
The project does not exist in this repository. Closing.
