### ISSUE TITLE
Passing a function from global scope to AudioWorkletProcessor

### ISSUE THREAD

**Issue by aatishb** [GoogleChromeLabs/web-audio-samples#152]
Apologies if this question is unclear or overly basic, I'm new to using audio worklets and the syntax is quite unfamiliar to me. I managed to get a simple example working of an audioWorkletNode firing up an audioWorkletProcessor. 

HTML: 
```
<!doctype html>
<html>
<script>
const audio = new AudioContext();

// Loads module script via AudioWorklet.
audio.audioWorklet.addModule('audio-processor.js').then(() => {
  let sound = new AudioWorkletNode(audio, 'audio-processor');
  sound.connect(audio.destination);
});

</script>
</html>

```

Javascript:
```
class AudioProcessor extends AudioWorkletProcessor {

  constructor(options) {
    super(options);
  }

  process(inputs, outputs, parameters) {
    let input = inputs[0][0];
    let output = outputs[0][0];
    let numSamples = output.length;

    loop(input, output, numSamples);

    return true;
  }
}

registerProcessor('audio-processor', AudioProcessor);

function loop(input, output, numSamples) {
  let amplitude = 0.1;
  for (let i = 0; i < output.length; ++i) {
    output[i] = 2 * (Math.random() - 0.5) * amplitude;
  }
}

```
Now I'd like to define a function in the global scope that can be passed to / accessed by the audioWorkletProcessor. e.g. I'd like to define the loop function in my main javascript code instead, and pass it to the audioWorklet. How can I do this?

**Comment by hoch** [comment]
How about something like this?

```js
const audioContext = new AudioContext();

async function loadModules() {
  // Load multiple modules sequentially.
  await audioContext.audioWorklet.addModule('my-library.js');
  return await audioContext.audioWorklet.addModule('audio-processor.js');
}

loadModules().then(() => {
  const workletNode = new AudioWorkletNode(audioContext, 'audio-processor');
  workletNode.connect(audioContext.destination);
});
```

I almost feel bad about mixing promise and await/async here, but the top-level await is not allowed. But I am sure this can be nicely abstracted with a couple of lines of code.

**Comment by hoch** [comment]
If that satisfies your purpose, nothing stops you from doing that. However, I would not say it is a pretty thing to look at.

By using async/await, you can precisely sequence the module loading with better readability.

**Comment by aatishb** [comment]
Thanks, I tried it out the way that you suggest. 

However, when I try to refer to a loop function defined in my-library.js from within the process function of the audioWorklet, I get the error: `Uncaught ReferenceError: loop is not defined at AudioWorkletProcessor.process`

I confirmed that the library is being loaded, but its variables seem to not be accessible from the worklet, which is what I'm hoping to achieve.

**Comment by hoch** [comment]
Hmm. I think you just found a bug. I filed [an issue in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=851123) and will investigate further.

Thanks for bringing it to here!

**Comment by hoch** [comment]
The isse was addressed in the [crbug thread](https://bugs.chromium.org/p/chromium/issues/detail?id=851123). Closing.
