### ISSUE TITLE
ConvolverNode buffer can only be set once

### ISSUE THREAD

**Issue by rtoy** [GoogleChromeLabs/web-audio-samples#156]
According to https://webaudio.github.io/web-audio-api/#dom-convolvernode-buffer, the `buffer` attribute can  only be set to a non-null value once.  Chrome is now enforcing this and produces the required error.  The [shiny-drum-machine demo](https://googlechromelabs.github.io/web-audio-samples/samples/audio/shiny-drum-machine.html) needs to be fixed.  There may be others.

**Comment by hoch** [comment]
This is not true anymore since we reverted the spec/impl change.
