### ISSUE TITLE
How to get error message in AudioWorklet onprocessorerror

### ISSUE THREAD

**Issue by aatishb** [GoogleChromeLabs/web-audio-samples#160]
The AudioWorklet [error catching example](https://googlechromelabs.github.io/web-audio-samples/audio-worklet/basic/node-onerror.html) shows how to catch an error, but directs the user to the console log to see the content of the error. I would like to know if there's a way to directly get the error from within javascript. The context is for building a live-coding environment where the error can be easily seen by the user.

**Comment by hoch** [comment]
On top of my head, something like this might be possible. Have not test, please file a bug if this does not work as expected:

```js
class ConstructorErrorProcessor extends AudioWorkletProcessor {
  constructor() {
    super();
    try {
      // Some codes here.
    } catch (error) {
      this.port.postMessage({ error: error });
    }
  }

  process() {
    try {
      // Some codes here.
    } catch (error) {
      this.port.postMessage({ error: error });
    }
    return true;
  }
}
```

It is more work but you need to deliver errors to the main thread to present them to the UI layer, which is on the main thread. Then the associated AudioWorkletNode will be able to handle the received an error object.

**Comment by aatishb** [comment]
Thanks, this works! I added a `throw error;` at the end of the catch statement to prevent it from spamming the message port with the same error.

**Comment by hoch** [comment]
That's a good point. Glad it worked out. It is unfortunate the WorkletGlobalScope doesn't have a way of serving up errors properly. This pattern can be a nice workaround.
