### ISSUE TITLE
Shared Buffer Design pattern bug

### ISSUE THREAD

**Issue by breznik** [GoogleChromeLabs/web-audio-samples#161]
There's a bug in the implementation of the Shared Buffer Design pattern sample code. If for example I add some simple code to the shared-buffer-worker on line 92: https://github.com/GoogleChromeLabs/web-audio-samples/blob/gh-pages/audio-worklet/design-pattern/shared-buffer/shared-buffer-worker.js#L92

```javascript
if (isNaN(InputRingBuffer[0][inputReadIndex])) {
  console.error('Found NaN at buffer index: %d', inputReadIndex)
}
```

When I then run the code, I always see a NaN at index 3072, which makes sense since the default ring buffer is of size 3072 and so nothing would be written into the buffer at that index, right? 

To fix:
that for loop should look like:
```javascript
for (let i = 0; i < CONFIG.kernelLength; ++i) {
  if (inputReadIndex === CONFIG.ringBufferLength) {
    inputReadIndex = 0;
  }

  OutputRingBuffer[0][outputWriteIndex] = InputRingBuffer[0][inputReadIndex];
  if (outputWriteIndex++ === CONFIG.ringBufferLength) {
    outputWriteIndex = 0;
  }
}
```

**Comment by breznik** [comment]
My proposed fix is incomplete, and after troubleshooting some more, I would suggest the following changes:

1) shared-buffer-worker.js
Make the for loop:
```javascript
for (let i = 0; i < CONFIG.kernelLength; ++i) {
  if (inputReadIndex === CONFIG.ringBufferLength) {
    inputReadIndex = 0;
  }

  OutputRingBuffer[0][outputWriteIndex] = InputRingBuffer[0][inputReadIndex];
    if (outputWriteIndex++ === CONFIG.ringBufferLength) {
      outputWriteIndex = 0;
    }

  inputReadIndex++
}
```

2) shared-buffer-worklet-processor.js#[_pushInputChannelData](https://github.com/GoogleChromeLabs/web-audio-samples/blob/gh-pages/audio-worklet/design-pattern/shared-buffer/shared-buffer-worklet-processor.js#L81)
Change the condition from `<` to `<=`:
```javascript
if (inputWriteIndex + inputChannelData.length <= this._ringBufferLength) {
```
I'm guessing `_pullOutputChannelData` will need a similar change, but I haven't reviewed that.

Also, more out of curiosity since this is example code, is there any benefit to having the Input/Output Ring Buffers be an array of SABs when they array size is just 1? i.e.:
`this._inputRingBuffer = [new Float32Array(sharedBuffers.inputRingBuffer)]` vs `this._inputRingBuffer = new Float32Array(sharedBuffers.inputRingBuffer)` ?

**Comment by hoch** [comment]
Thanks for the suggestion! It looks like I need to check the all the indexes again. Sorry for the hassle.
