### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by lc-leoniefarmer** [GoogleChromeLabs/web-audio-samples#171]
The "see sources on github" link in the demo page (https://googlechromelabs.github.io/web-audio-samples/audio-worklet/design-pattern/wasm/) is broken. Goes to 404 error page.

**Comment by hoch** [comment]
I'll fix it. The link is supposed to be: https://github.com/GoogleChromeLabs/web-audio-samples/tree/master/audio-worklet/design-pattern/wasm/

**Comment by hoch** [comment]
It should be fixed now. Feel free to reopen if you find problems again.

**Comment by lc-leoniefarmer** [comment]
That's great. Thanks
