### ISSUE TITLE
More of a question than an issue: about code in shared-buffer-worker.js

### ISSUE THREAD

**Issue by dorontal** [GoogleChromeLabs/web-audio-samples#173]
Hello, first of all thank you so much for this incredibly useful contribution as it is the only piece of code that would allow me to do what I wish to do (full-duplex multi-track recorder and more, in your browser) that I could find on the entire world wide web.

Please accept my apology if this is a stupid question, also, I wasn't sure where to post it, but I was wondering why, in  web-audio-samples/audio-worklet/design-pattern/shared-buffer/shared-buffer-worker.js, you make the input ring buffer and the output ring buffer an array of one element, each, where the one element is the actual buffer. That seems to be one extra pointer to pass around and I was thinking there must be a reason why it is done this way. On lines 162-3, you have
```
    InputRingBuffer = [new Float32Array(SharedBuffers.inputRingBuffer)];
    OutputRingBuffer = [new Float32Array(SharedBuffers.outputRingBuffer)];
```
and these are used as such in the `processKernel()` function:
```
    for (let i = 0; i < CONFIG.kernelLength; ++i) {
        OutputRingBuffer[0][outputWriteIndex] = InputRingBuffer[0][inputReadIndex];
        ...
```
wouldn't it work to use, instead:
```
    InputRingBuffer = new Float32Array(SharedBuffers.inputRingBuffer);
    OutputRingBuffer = new Float32Array(SharedBuffers.outputRingBuffer);

    ... & ...

    for (let i = 0; i < CONFIG.kernelLength; ++i) {
        OutputRingBuffer[outputWriteIndex] = InputRingBuffer[inputReadIndex];
        ...
```
(I'm about to write code based on this worker code, so if I test it, I will let you know).
Thanks!

**Comment by dorontal** [comment]
Got it, thanks so much!  And thanks again for sharing this code - extremely useful!

**Comment by hoch** [comment]
Glad it helped!
