### ISSUE TITLE
Doesn't SharedArrayBuffer model end up with race condition?

### ISSUE THREAD

**Issue by orange4glace** [GoogleChromeLabs/web-audio-samples#177]
On [SharedArrayBuffer](https://github.com/GoogleChromeLabs/web-audio-samples/blob/master/audio-worklet/design-pattern/shared-buffer/shared-buffer-worklet-processor.js#L106) model, as Iong as I think, there's no lock behavior on [`_pullOutputChannelData`](https://github.com/GoogleChromeLabs/web-audio-samples/blob/master/audio-worklet/design-pattern/shared-buffer/shared-buffer-worklet-processor.js#L106).

If so, when [`processKernel`](https://github.com/GoogleChromeLabs/web-audio-samples/blob/master/audio-worklet/design-pattern/shared-buffer/shared-buffer-worker.js#L85) on `WorkerThread` takes heavy time, then eventually `AudioWorkletThread` will read same memory which is still writing by `WorkerThread` and it will ends up with race condition.
It seems that the code assumes `processKernel` will takes very tiny amount of time so such race condition will not happen. 

Is it right?

**Comment by hoch** [comment]
You concern/analysis is correct. The race condition is possible. I have been meaning to update the code with more strict checks, but that hasn't happen yet.

If you have an idea to improve the design, PR is always open. :)

**Comment by orange4glace** [comment]
Possible solutions I thought :

1. Send message when output buffer is ready via MessagePort
2. Block AWP until output buffer is ready using spin-lock

But neither of them seems to have a problem. 

1. Main UI thread must get involved as a relay in message passing between AWP and DWG. As a result, there might be a delay issue when UI thread is kinda busy.
2. Spin-lock performance issue

I had thought that using `Atomics.wait` on AWP can be one of the solution but it turns out AWP disables `Atomics.wait`. Is there any reason AWP disables it?

**Comment by hoch** [comment]
I think the linked spec discussion explains the reason. Please re-open this if needed.
