### ISSUE TITLE
JSON is not correct...

### ISSUE THREAD

**Issue by danzen** [GoogleChromeLabs/web-audio-samples#193]
If these are supposed to be JSON files, they should have double quotes instead of single quotes and there should not be trailing commas.  It they are js files, I don't think you can {} on a line it would be assigned to a variable.  Cheers.

**Comment by hoch** [comment]
Do you have the source location of this problem?

**Comment by danzen** [comment]
Hi @hoch - I do but I am loading in through ZIM so perhaps not a universal example (it uses CreateJS in the back to file load and parse JSON).  Just in general... https://jsonlint.com/ for instance, single quotes are not valid JSON.  And... to get the file to load as JS I think you have to assign all that to a variable and then it works just as an object literal.  Also... IE (even 11 I think) does not work with trailing commas - I could be wrong - and there are trailing commas in all of them.  If it is helpful, here is a zip of adjusted files.  I have renamed them json files - I am not sure how you folks are using them.  Cheers.
[waves.zip](https://github.com/GoogleChromeLabs/web-audio-samples/files/4584370/waves.zip)

**Comment by hoch** [comment]
I am not still following you. Could you provide a link to the problem in this repository? Which example? Which file? Which line?

**Comment by danzen** [comment]
Oh!  I am so sorry... this is a really big library - lol - I did not realize how many files are here.  The wavetables - are close to JSON but just a few issues.  I don't know if you have some other programming language reading them - if that's so fine.  But it is a simple matter... if they are supposed to be JSON... they are not quite for the reason stated earlier.  https://github.com/GoogleChromeLabs/web-audio-samples/tree/gh-pages/samples/audio/wave-tables

**Comment by mr21** [comment]
Indeed, the `real` and `imag` attributes are in quotes (asked by json) but there are trailing commas and this is also forbidden in JSON..

`JSON.parse('{a:1,}'); // error`

**Comment by danzen** [comment]
Currently, the attributes are in single quotes and they should be double quotes.
{
'real': [
// should be 
{
"real": [

**Comment by mr21** [comment]
Oh indeed i forgot that, those files are probably directly include in the HTML, and parsed as JS

**Comment by hoch** [comment]
Ah. It is a really old example. If you're willing to make a PR with the fix, I am happy to review it.

**Comment by sukhbir192000** [comment]
Hey, I would like to fix this issue. I just wanted to confirm if all I needed to do was to convert the single quotes to double quotes or  I also need to remove the trailing commas.

**Comment by danzen** [comment]
@sukhbir192000 - thanks - IE (even 11 I think) does not work with trailing commas - I could be wrong... but it is pretty easy to remove them just in case.  Cheers.

**Comment by hoch** [comment]
Fixed by #204
