### ISSUE TITLE
Audio Worklet and WebAssembly Error: Module resolve hook not set

### ISSUE THREAD

**Issue by semohr** [GoogleChromeLabs/web-audio-samples#197]
AudioWorklet and WebAssembly examples not working and console gives:
```
Error: Module resolve hook not set
```

Using **Firefox** 78.0.1.

I also found [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1636121), which seems to be related.

**Comment by hoch** [comment]
Is this a problem in the example code? It seems like the problem is some browsers are not supporting ES6 modules in Worklet. No?

**Comment by semohr** [comment]
Yes I had this problem for the examples with worklets if I remember correctly. Not sure if it is fixed by now but from the bugzilla it does not seem like it.

**Comment by hoch** [comment]
I believe the problem you see in other browsers needs to be fixed there, not the example code here. The linked bugzilla issue is a proper venue to continue the discussion.
