### ISSUE TITLE
An example of a DJ turntable, implemented using a worklet.

### ISSUE THREAD

**Issue by carlsmith** [GoogleChromeLabs/web-audio-samples#200]
I have a small, simple implementation of a turntable (or *deck*), implemented as an `AudioWorkletProcessor`. It defines a `pitch` param that allows the turntable to play at any speed (forwards or backwards) with perfectly adequate fidelity (using linear interpolation, in JavaScript).

It seemed like a good candidate for an example project, and I just wondered if you have a use for something like that?? I'm planning to redo the core logic in (hand-written) WebAssembly, and could fork off an example from that version too/instead. Just lemme know.

P.S. I'm struggling to find a short music file that is free of licensing issues. Any suggestions would be appreciated.

**Comment by hoch** [comment]
Perhaps it's better to contact the editor of Web Audio Weekly for your project:
https://www.webaudioweekly.com/

Also you can share your project with the Web Audio Slack channel:
https://web-audio-slackin.herokuapp.com/

**Comment by carlsmith** [comment]
Thanks, @hoch.
