### ISSUE TITLE
Atomics.wake is not a function at AudioWorkletProcessor.process (shared-buffer-worklet-processor.js:145)

### ISSUE THREAD

**Issue by chaosprint** [GoogleChromeLabs/web-audio-samples#202]
try to run the example on:
https://googlechromelabs.github.io/web-audio-samples/audio-worklet/design-pattern/shared-buffer/
but it either makes the page completely crashed (Aw Snap) or throws this error:
```
Uncaught TypeError: Atomics.wake is not a function
    at AudioWorkletProcessor.process (shared-buffer-worklet-processor.js:145)
process @ shared-buffer-worklet-processor.js:145
```
looks like the issue comes from this line:
```
Atomics.wake(this._states, STATE.REQUEST_RENDER, 1);
```

**Comment by hoch** [comment]
Fixed by #198.
