### ISSUE TITLE
unclear error message " /* #ignore */ console.warn('crbug/1173575, non-JS module files deprecated.');

### ISSUE THREAD

**Issue by yishengjiang99** [GoogleChromeLabs/web-audio-samples#211]
on one hand it says *ignore*, on the other hand it is console WARN. and then i assume crbug stands for CRITICAL bug?
im unclear on how much worried I should be abou this.

triggered by wavetable.js's load() function. pr to fix inc.

**Comment by hoch** [comment]
What's the code location you're referring to?

**Comment by hoch** [comment]
We'll wait for one more week before closing this.

**Comment by yishengjiang99** [comment]
Hey I saw it on my localhost. but do not see it on current version of the production code today.
