### ISSUE TITLE
WASMAudioBuffer free of undefined ptr.

### ISSUE THREAD

**Issue by jadujoel** [GoogleChromeLabs/web-audio-samples#238]
in [WASMAudioBuffer](https://github.com/GoogleChromeLabs/web-audio-samples/blob/main/audio-worklet/design-pattern/wasm-supersaw/util/WASMAudioBuffer.js) in the free method. One line confuses me: `this._module._free(this._pointerArrayPtr);`. But _pointerArrayPtr is not defined anywhere else as far as I can see. Is this just a bug or am I missing something?

**Comment by hoch** [comment]
Thanks for catching. Probably the bug came from the previous repository while we're cloning the code. Fixed now!
