### ISSUE TITLE
Missing headers in wasm-supersaw index.html file

### ISSUE THREAD

**Issue by yogesh0509** [GoogleChromeLabs/web-audio-samples#241]
There are some missing header files in [https://github.com/GoogleChromeLabs/web-audio-samples/blob/main/audio-worklet/design-pattern/wasm-supersaw/index.html](url) due to which the wasm-supersaw page when run in local environment misbehaves.

**Comment by yogesh0509** [comment]
I can create a pull request to fix this bug

**Comment by hoch** [comment]
Yes. That would be a good "starter bug"!
