### ISSUE TITLE
Link to lit documentation is out-of-date

### ISSUE THREAD

**Issue by rowild** [GoogleChromeLabs/web-audio-samples#244]
This article:

https://github.com/GoogleChromeLabs/web-audio-samples/tree/main/assets/lit-html

links to a non-existing lit-documentation link. It seems to me that this one would be the actual one nowadays:

https://lit.dev/docs/

If you agree, I'm happy to provide a PR!

**Comment by hoch** [comment]
Yes, please! I would appreciate a PR.

**Comment by rowild** [comment]
It's been some time, I hope I found the proper place:
#249 

Please also check a paragraph about lit's development status, which I changed also.
For me it would be totally fine if you reformulate and add/remove/change things in this PR.

Thank you!

**Comment by hoch** [comment]
Closed by #246.

Thank you @rowild!
