### ISSUE TITLE
The source code link on the AudioWorklet example leads nowhere

### ISSUE THREAD

**Issue by greggman** [GoogleChromeLabs/web-audio-samples#256]
This page

https://googlechromelabs.github.io/web-audio-samples/audio-worklet/basic/hello-audio-worklet/

Has a "source code" link that leads no where

**Comment by hoch** [comment]
Yeap. This is a bug we want to fix. The PR is here, but needs review:
https://github.com/GoogleChromeLabs/web-audio-samples/pull/248

**Comment by hoch** [comment]
#248 is merged.
