### ISSUE TITLE
AudioWorkletRecorder demo is broken

### ISSUE THREAD

**Issue by hoch** [GoogleChromeLabs/web-audio-samples#261]
Reproduction steps:
1. Go to https://googlechromelabs.github.io/web-audio-samples/audio-worklet/migration/worklet-recorder/
2. Change maxFrameCount: context.sampleRate*10 to  maxFrameCount: context.sampleRate*100 to record more than 10s in app.js
3. Record > 30s of audio playing from another tab
4. Playback the audio. You'll see the audio is distorted after 30s

At least this is reproducible on Mac.

**Comment by hoch** [comment]
The important step is 3. The distortion happens only when the tab goes background.

**Comment by chrisguttandin** [comment]
Could this be the same bug as reported [here](https://bugs.chromium.org/p/chromium/issues/detail?id=995124)?

**Comment by hoch** [comment]
I have a fix under development - but to answer your question, this example uses AW not MediaRecorder.

**Comment by chrisguttandin** [comment]
Sorry, my bad. I linked to the wrong bug. I meant this one. https://bugs.chromium.org/p/chromium/issues/detail?id=1016104

**Comment by yefim** [comment]
None of the recording demos work

**Comment by hoch** [comment]
@yefim Can you elaborate a bit more? What was not working?

**Comment by yefim** [comment]
1. Go to https://googlechromelabs.github.io/web-audio-samples/audio-worklet/migration/worklet-recorder/
2. Click start recording like 2 or 3 times
3. Click stop recording
4. Watch it do nothing

What I expect:

I want to be able to preview and download my recording

**Comment by TenghuiZhang** [comment]
@yefim Hi, I was not able to reproduce this issue. Could you help me provide some details or video recording relate to the issue which you mention?

**Comment by TenghuiZhang** [comment]
Since this issue seems resolve, I am going to close this issue. Feel free to reopen it if there is any broken demo or link.

**Comment by yefim** [comment]
Here's a video of the recorder demo not working. I recorded myself speaking but cannot play it back. https://streamable.com/3w2gsy
