### ISSUE TITLE
Start button is not woking when you do click once.

### ISSUE THREAD

**Issue by SoumyaSubhrajit** [GoogleChromeLabs/web-audio-samples#299]
1) When i do checking in the site I found when I click the `start-button` it not working at first, it just turn on my recording, then 
    when I click the button **once more** then the recording is on, don't you think that's a little confusing for the new comer,.

https://user-images.githubusercontent.com/112542453/233736668-1e1766fe-eb74-4a0c-aade-96076e701ee4.mp4

2)There is no reset button anywhere to restart the whole thing, you have to reload the page to record.
I do leave video footage do check out.

if have anything in reply I am more than happy to listen to the feedback.

**Comment by TenghuiZhang** [comment]
Thanks for providing this feedback! We are trying our best to provide a better user experience demo. The reason the first click is required is due to the auto-play policy. Sorry for the inconvenience of not having a reset button. We rewrote a better description/user guide above the demo.

**Comment by SoumyaSubhrajit** [comment]
@TenghuiZhang can I try to work with this issue..

**Comment by TenghuiZhang** [comment]
Sure, please submit a PR and add me as the reviewer.

**Comment by SoumyaSubhrajit** [comment]
@TenghuiZhang ok on it.

**Comment by hoch** [comment]
@SoumyaSubhrajit Do we have any updates on this? Otherwise, we'll make this available again.

**Comment by TenghuiZhang** [comment]
@SoumyaSubhrajit
This issue is fixed in PR #326. Feel free to open new issue if you have any new finding.
