### ISSUE TITLE
Upgrade the build tool to 11ty 2.x

### ISSUE THREAD

**Issue by hoch** [GoogleChromeLabs/web-audio-samples#305]
Some NPM modules for the site generator are outdated. Upgrade them. There are some braking changes from 11ty 1.x to 2.x, so do research before making the transition.

**Comment by SoumyaSubhrajit** [comment]
Hi, @hoch I updated **@11ty/eleventy** , **@11ty/eleventy-navigation**, and **tailwindcss**, I check the website, and in the terminal no such error showing for now.
I feel these 3 are modules are relevant to update, as they are used in the site generator, so do you want me to check the newly updated module's bugs in code or update the rest of the modules as well?

**Comment by hoch** [comment]
Thanks for looking into this. If you already have the change in hand, can you create a PR so we can review it?
