### ISSUE TITLE
 Request: Centered Heading "Web Audio/MIDI Samples"

### ISSUE THREAD

**Issue by YashMishra0101** [GoogleChromeLabs/web-audio-samples#323]
The objective of this issue is to enhance the visual presentation of the project by centering the heading "Web Audio/MIDI Samples". Currently, the heading appears aligned to the left, resulting in a slightly imbalanced layout. To address this, I propose making minor changes to the project's CSS code to ensure the heading is centered. This adjustment will significantly improve the visual appeal and balance of the design.

I kindly request the project maintainers to assign this issue to me so that I can proceed with the necessary changes.

**Comment by hoch** [comment]
Thanks for your inquiry, but we don't have a plan to change as suggested: The text alignment (left) is consistent across all pages in the site.

**Comment by YashMishra0101** [comment]
Okay, not a problem. Thank you for your response.

**Comment by hoch** [comment]
Thanks for your interest in the project! Please feel free to raise other suggestions if you have any.
