### ISSUE TITLE
Revise the description text: short and simple.

### ISSUE THREAD

**Issue by TenghuiZhang** [GoogleChromeLabs/web-audio-samples#334]
Change to description of SPN and worklet page

**Comment by TenghuiZhang** [comment]
SPN recorder description: 
Demonstrates a simple recording app using ScriptProcessorNode which can record up to 5 minutes. Stops automatically and provides a download link for the recorded .wav file. May take a moment to prepare the link and preview the recording. Click Refresh to start a new recording.

Worklet recorder description: 
Demonstrates a simple recording app using AudioWorklet API which can record up to 5 minutes. Stops automatically and provides a download link for the recorded .wav file. May take a moment to prepare the link and preview the recording. Click Refresh to start a new recording.

**Comment by hoch** [comment]
Perhaps:

A simple audio recorder built with {ScriptProcessorNode, AudioWorkletNode} can record up to 5 minutes and stops automatically. Upon completion, it provides a downloadable link for the recorded audio file (PCM Wave). It may take a few seconds to build and preview the recording. Click Refresh to start a new recording.
