### ISSUE TITLE
Improve RingBuffer

### ISSUE THREAD

**Issue by hoch** [GoogleChromeLabs/web-audio-samples#347]
A comment from @mjwilson-google: 

> The way we're reading or writing the samples is also kinda strange; we could probably just be updating the index directly instead of making a new temporary every iteration. But that at least looks like it's correct, just inefficient. If we updated the index directly each iteration we wouldn't need to do the correction after the loop at all.

I say we should prioritize improving our AudioWorklet examples because it is often used/referred by developers.

**Comment by mjwilson-google** [comment]
This was referencing https://github.com/GoogleChromeLabs/web-audio-samples/blob/main/src/audio-worklet/design-pattern/lib/wasm-audio-helper.js but it seems like we have some other ring buffer implementations as well that might be worth looking at too.

**Comment by Daksh-10** [comment]
@hoch @mjwilson-google I worked on this issue and created a pull request #352

**Comment by hoch** [comment]
This is a tracking issue for improving the RingBuffer. The PR above can be considered one task that we completed.

**Comment by hoch** [comment]
@professorabhay is working on this:
https://github.com/GoogleChromeLabs/web-audio-samples/issues?q=is%3Aopen+author%3Aprofessorabhay
