### ISSUE TITLE
Research various JS testing frameworks

### ISSUE THREAD

**Issue by hoch** [GoogleChromeLabs/web-audio-samples#365]
- Research various JS testing frameworks (e.g. An article from [BrowserStack](https://www.browserstack.com/guide/top-javascript-testing-frameworks))
- Prioritize frameworks that offer robust support for asynchronous testing and mocking of Web Audio APIs

**Comment by hoch** [comment]
@terryzfeng @Kizjkre I think we can use this issue to record/document the research. What do you think?

**Comment by hoch** [comment]
This looks pretty comprehensive, but I haven't checked on how to capture/analysis audio output:
https://playwright.dev/

**Comment by hoch** [comment]
Some criteria to consider:
- Widely known and stable.
- Less overhead is better; we only need something that can run/measure the Web Audio API.
- It can run the realtime AudioContext and capture the rendered audio result.
- It can measure the audio rendering performance.
- (Stretch) It can run on the latest Chromium automatically via GitHub's CI.

**Comment by terryzfeng** [comment]
Base Questions: Which test frameworks are:
1. Easy to use / documented 
2. Realtime use and Headless (for CI)
3. Uses actual audio driver

**Comment by terryzfeng** [comment]
Here is the research/findings/documentation I have for the Playwright framework. Learning Playwright became quite involved and I needed to write myself a README. 

https://docs.google.com/document/d/1e7G9jc4kuVZWvjylTtFE76DzQBsOG6lZSFmV19Kc5cY/edit

**Comment by terryzfeng** [comment]
@Kizjkre I added no-user-gesture-required but I don't think it works with Firefox, so the tests weren't compatible..

**Comment by terryzfeng** [comment]
Linking the PR for Playwright: https://github.com/GoogleChromeLabs/web-audio-samples/pull/368
