### ISSUE TITLE
iso cannot paly sound

### ISSUE THREAD

**Issue by lqh1008** [GoogleChromeLabs/web-audio-samples#379]
mac and windows can paly sound，ios cannot

**Comment by mjwilson-google** [comment]
Hello, I think we need some more information.

Is there a particular example you are trying to use that will play sound on Mac and Windows, but not iOS?

What browser are you using?

Note that this issue tracker is only for the web-audio-samples repository.  If there are general iOS issues those should probably be filed somewhere else.

**Comment by hoch** [comment]
Closing due to the lack of feedback from the reporter.
