### ISSUE TITLE
gh-pages deployment doesn't build non-HTML/JS files.

### ISSUE THREAD

**Issue by Kizjkre** [GoogleChromeLabs/web-audio-samples#382]
The [live suite](https://googlechromelabs.github.io/web-audio-samples/tests/playwright/pages/) fetches a `live-suite/style.css` and a reference file `reference/440@48k-sine-octx.json`. While these files exist on the `main` branch, `gh-pages` doesn't have the same files: https://github.com/GoogleChromeLabs/web-audio-samples/tree/c29cec74c47e58b95def50eb8c166bcfb88e45e7/tests/playwright/pages. This causes the live suite to break when not run locally.

**Comment by hoch** [comment]
I've looked at the PR, but adding `cp` to individual files doesn't looks like a future-proof solution.

I think we need to dig a bit deeper to figure out why this is happening.

**Comment by mjwilson-google** [comment]
I think any files you want copied over should be added to the [passthrough list in .eleventy.js](https://github.com/GoogleChromeLabs/web-audio-samples/blob/main/.eleventy.js#L46)
