### ISSUE TITLE
Remove zero-crossings.html

### ISSUE THREAD

**Issue by rtoy** [GoogleChromeLabs/web-audio-samples#48]
Not exactly sure what this is trying to demonstrate and how it relates to webaudio.

Remove this?

**Comment by hoch** [comment]
I think its intention is to find valid looping points in a buffer. Some of codes might be useful when building a waveform editor.

**Comment by cwilso** [comment]
I'm on the fence.  It's pretty much completely uncommented and fairly
opaque.  I'm inclined to leave it in but not highlight it.
