### ISSUE TITLE
Repository reboot

### ISSUE THREAD

**Issue by hoch** [GoogleChromeLabs/web-audio-samples#63]
Many files are known to be outdated and the overall structure of the repository is a bit odd. Here are the proposed changes:
1. Remove irrelevant and redundant files.
2. Apply a template to all the demo HTML files that includes:
   - short description, last updated dates, working Chrome version
   - an analytics script for all the URL in the repository.
3. Redesign the index page with Polymer.

@rtoy and @cwilso - please let me know if you have any concerns or ideas about this change.

**Comment by cwilso** [comment]
SGTM.

**Comment by rtoy** [comment]
SGTM, with a couple of items.  

What does "working Chrome version" mean?
How will you determine which files are irrelevant?  I guess a pull request for the removal is good enough.

**Comment by hoch** [comment]
> What does "working Chrome version" mean?

I am thinking of placing a json file into each sample file. 'Working Chrome version' means the last known working version/revision. This can be automated to some extent, I believe.

> How will you determine which files are irrelevant? I guess a pull request for the removal is good enough.

Yes, I will make sure you and cwilso@ can review the changes.

**Comment by hoch** [comment]
This is done with the landing V2 site.
