### ISSUE TITLE
Web Audio Demo: WD-1 DJ-TRAINER

### ISSUE THREAD

**Issue by WortelDrie** [GoogleChromeLabs/web-audio-samples#70]
Hi,
A musical keyboard with 22 soundbanks. From Techno to Samba. 
The first DJ-TRAINER was a Flash application firstly built in 2003. Now I managed to rebuilt the machine with Web Audio Api. I've used [bufferloader.js](https://gist.github.com/shinnn/5584977) (for the loops), [howler.js](https://github.com/goldfire/howler.js/) (for the triggered sounds) and [nouislider](https://github.com/leongersen/noUiSlider/) to make the frequency slider work on touchscreens.
Check it out at my website: [WortelDrie.com](http://worteldrie.com/WD5/).

**Comment by hoch** [comment]
This repository does not accept submission for external demos.
