### ISSUE TITLE
Web MIDI Demo: Assistant Performer

### ISSUE THREAD

**Issue by notator** [GoogleChromeLabs/web-audio-samples#71]
Hi, maybe you'd like to add this to your demos?

This is a developing, experimental Web MIDI application that plays scores stored in an SVG format which has been enhanced to contain MIDI information. In development is the ability to play scores live using MIDI input devices. 

The latest stable version can be found at:
http://james-ingram-act-two.de/open-source/assistantPerformer/assistantPerformer.html.
GitHub repository: https://github.com/notator/assistant-performer

**Comment by hoch** [comment]
This repository does not accept submission for external demos.
