### ISSUE TITLE
Web Audio Demo: WebMIDISynthHost / ResidentSf2Synth

### ISSUE THREAD

**Issue by notator** [GoogleChromeLabs/web-audio-samples#72]
Hi, maybe you'd like to have this too?

The WebMIDISynthHost hosts four GUI-less Web Audio synthesizers that can be copied and used on any web site. The browser must support Web Audio, but does not need to support Web MIDI.

Web app: http://james-ingram-act-two.de/open-source/WebMIDISynthHost/host.html 
GitHub: https://github.com/notator/WebMIDISynthHost

One of the hosted synths is the ResidentSf2Synth. (This is also used by my Assistant Performer app.)
I am not a Web Audio specialist, so would especially welcome help in developing it.
GitHub: https://github.com/notator/residentSf2Synth

**Comment by hoch** [comment]
This repository does not accept submission for external demos.
