### ISSUE TITLE
New `audio-worklet` directory

### ISSUE THREAD

**Issue by hoch** [GoogleChromeLabs/web-audio-samples#80]
Currently @samhincks is working on a PR that adds few demo projects for AudioWorklet, but we need to think about utilizing the directory for other purposes. I proposed to structure the directory as shown below:

```bash
# repository root
audio-worklet/
    basic/
    bit-crusher/
    lib/          # project-wide JS libraries (audit.js?)
    resources/    # project-wide images or stylesheets
    noise-gate/
    index.html
```

Each subdirectory can have demo-specific JS/HTML/CSS files:

```bash
audio-worklet/
    bit-crusher/
        js/
        resources/
        index.html
        test.html
```

@rtoy @samhincks WDYT?

**Comment by hoch** [comment]
For the naming of directory, we should stick to "lower-cased and hyphenated" style. The class name is commonly camelized, so the file name that contains the class should be translated accordingly.

**Comment by rtoy** [comment]
SGTM.

What is "basic" for?

I assume each demo like bit-crusher/noise-gate should, more or less, be self-contained, and not share too much?  So lib and resources are truly audio-worklet wide items.

**Comment by samhincks** [comment]
SGTM. The source controller and param controller would be shared. And I'm also building a test class with generally useful methods.

**Comment by hoch** [comment]
> What is "basic" for?

Some basic demonstrations on how AudioWorklet works.

> I assume each demo like bit-crusher/noise-gate should, more or less, be self-contained, and not share too much? So lib and resources are truly audio-worklet wide items.

That's my intention.

> The source controller and param controller would be shared. And I'm also building a test class with generally useful methods.

Sure.

**Comment by qlamerand** [comment]
Hi,
Sorry to ask that here but how can I test these example?
Thanks in advance

**Comment by hoch** [comment]
@qlamerand This feature is not shipped yet, but you can try out if you're willing to build Chromium from scratch with [this patch](https://codereview.chromium.org/2793593002/). FYI, it is not throughly tested.

**Comment by qlamerand** [comment]
@hoch Thanks! I'll try that :)

**Comment by hoch** [comment]
V2 is landed with the newly design sub site for Audio Worklet. Closing.
