### ISSUE TITLE
audio-worklet/src/param-controller.js is a dependency for the poly-synth

### ISSUE THREAD

**Issue by samhincks** [GoogleChromeLabs/web-audio-samples#90]
The poly-synth demo depends on "/audio-worklet/src/param-controller.js". This file should instead belong to a general directory.

**Comment by hoch** [comment]
We can create `lib/` directory in the root. In fact, how about moving all 'generic UI element' classes to that directory?

**Comment by samhincks** [comment]
Does that include audio-worklet/lib/audio-worklet-helper.js as well? Or only the param-controller and source-controller classes?

**Comment by hoch** [comment]
After landing V2 pages, this is not relevant anymore.
