### ISSUE TITLE
Noisegate needs threshold dB test

### ISSUE THREAD

**Issue by rtoy** [GoogleChromeLabs/web-audio-samples#94]
The noisegate node needs a test to verify that a selected noisegate threshold in dB actually opens and closes when a signal matches that dB value.

This can be done by setting the threshold to, say, -3 dB.  Generate a sine wave with a power of -3 dB.  Send this to the noise gate.  The noise gate should not open because (at least for a long time) because the envelope follower won't actually quite reach -3 dB.  That's one test.

The second test is to slightly increase the sine wave power to just above -3 dB.  The noise gate should open, eventually.  Equivalently, decrease the threshold to just below -3 dB.  Again, the gate should open since the input signal power is above the threshold.

**Comment by rtoy** [comment]
Oh.  This test is important because it verifies that the noise gate threshold actually matches the input power closely.

**Comment by hoch** [comment]
The project does not exist in this repository. Closing.
